### ISSUE TITLE
tonConnectUI.setConnectRequestParameters can't  work 

### ISSUE THREAD

**Issue by TroyMa1990** [TownSquareXYZ/tonconnect-ui-vue#13]
these code can't work, can't receive `wallet.connectItems?.tonProof`, please help, thank you!

````````
  const payload = { tonProof: "xxxxxxx" };
  tonConnectUI.setConnectRequestParameters("ready",state: "ready",value: payload);
  tonConnectUI.onStatusChange(wallet => {
  if (wallet.connectItems?.tonProof && 'proof' in wallet.connectItems?.tonProof) {
  ..
  }
  });
````````

**Comment by TroyMa1990** [comment]
close it, I resolve it

''''
onMount(
...
  if(!proof){
     tonConnectUI.disconnect()
  }
)
''''
then connect wallet by touch reconnect button, and you will get proof.

**Comment by Julietnacy** [comment]
@TroyMa1990 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Ton Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by ngocdangrby** [comment]
same here

**Comment by ngocdangrby** [comment]
i found this method to set proof in the doc. and its worked 
```
tonConnectUI.setConnectRequestParameters({
    state: 'ready',
    value: {
        tonProof: '<your-proof-payload>'
    }
});
```

**Comment by sansx** [comment]
@TroyMa1990 hey! which version of tonnect-ui-vue, and vue are you using now, you can check our demo repo first, it should have fully example there, https://github.com/TownSquareXYZ/demo-dapp-with-vue-ui/tree/main
