### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by afeezaziz** [TownSquareXYZ/tonconnect-ui-vue#2]
I am trying to npm install via github. I am getting this error: 

`Failed to resolve entry for package "@townsquarexyz/ui-vue". The package may have incorrect main/module/exports specified in its package.json.`

**Comment by lowskii** [comment]
same problem

**Comment by amirsafaricg** [comment]
Same

**Comment by infinityspectra** [comment]
We didn't really release the package, but still thanks for your attention. 

We just finished the code and published it. It should work now.
