### ISSUE TITLE
Nuxt 3

### ISSUE THREAD

**Issue by mahdi4187** [TownSquareXYZ/tonconnect-ui-vue#3]
Hi 👋 

Can I use in nuxt 3?

**Comment by kennysin1444** [comment]
It works well on mobile, but it's not working properly on PC and web.

**Comment by cici090** [comment]
> Hi 👋
> 
> Can I use in nuxt 3?

Hi, sorry for the late reply, this can be used in the next 3 , and welcome to use it!😄
